[tool.poetry]
name = "bot"
version = "0.1.0"
description = ""
authors = ["20jun01 <10junjun20@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.104.0"
uvicorn = "^0.23.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
