from enum import Enum

class EventType(Enum):
    PING = "PING"
    JOINED = "JOINED"
    LEFT = "LEFT"
    MESSAGE_CREATED = "MESSAGE_CREATED"
    MESSAGE_UPDATED = "MESSAGE_UPDATED"
    MESSAGE_DELETED = "MESSAGE_DELETED"
    BOT_MESSAGE_STAMPS_UPDATED = "BOT_MESSAGE_STAMPS_UPDATED"
    DIRECT_MESSAGE_CREATED = "DIRECT_MESSAGE_CREATED"
    DIRECT_MESSAGE_UPDATED = "DIRECT_MESSAGE_UPDATED"
    DIRECT_MESSAGE_DELETED = "DIRECT_MESSAGE_DELETED"
    CHANNEL_CREATED = "CHANNEL_CREATED"
    CHANNEL_TOPIC_CHANGED = "CHANNEL_TOPIC_CHANGED"
    USER_CREATED = "USER_CREATED"
    STAMP_CREATED = "STAMP_CREATED"
    TAG_ADDED = "TAG_ADDED"
    TAG_REMOVED = "TAG_REMOVED"
    USER_GROUP_CREATED = "USER_GROUP_CREATED"
    USER_GROUP_UPDATED = "USER_GROUP_UPDATED"
    USER_GROUP_DELETED = "USER_GROUP_DELETED"
    USER_GROUP_MEMBER_ADDED = "USER_GROUP_MEMBER_ADDED"
    USER_GROUP_MEMBER_UPDATED = "USER_GROUP_MEMBER_UPDATED"
    USER_GROUP_MEMBER_REMOVED = "USER_GROUP_MEMBER_REMOVED"
    USER_GROUP_ADMIN_ADDED = "USER_GROUP_ADMIN_ADDED"
    USER_GROUP_ADMIN_REMOVED = "USER_GROUP_ADMIN_REMOVED"

    @classmethod
    def value_of(cls, target_value):
        for e in EventType:
            if e.value == target_value:
                return e
        raise ValueError('{} is not valid event type.'.format(target_value))
